//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatServiceLib
{
    using System;
    using System.Runtime.Serialization;

    public class Client
    {
        public string Name;
        public Guid ServerGuid;
        public string FreeDesc;
    }

}
